/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-26 at 04:16:56 UTC 
 * Modify at your own risk.
 */

package com.noisyflowers.landpks.server.gae.model.transectendpoint;

/**
 * Service definition for Transectendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TransectendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Transectendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the transectendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://silicon-bivouac-496.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "transectendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Transectendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Transectendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTransect".
   *
   * This request holds the parameters needed by the transectendpoint server.  After setting any
   * optional parameters, call the {@link GetTransect#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTransect getTransect(java.lang.String id) throws java.io.IOException {
    GetTransect result = new GetTransect(id);
    initialize(result);
    return result;
  }

  public class GetTransect extends TransectendpointRequest<com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect> {

    private static final String REST_PATH = "transect/{id}";

    /**
     * Create a request for the method "getTransect".
     *
     * This request holds the parameters needed by the the transectendpoint server.  After setting any
     * optional parameters, call the {@link GetTransect#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetTransect#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTransect(java.lang.String id) {
      super(Transectendpoint.this, "GET", REST_PATH, null, com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTransect setAlt(java.lang.String alt) {
      return (GetTransect) super.setAlt(alt);
    }

    @Override
    public GetTransect setFields(java.lang.String fields) {
      return (GetTransect) super.setFields(fields);
    }

    @Override
    public GetTransect setKey(java.lang.String key) {
      return (GetTransect) super.setKey(key);
    }

    @Override
    public GetTransect setOauthToken(java.lang.String oauthToken) {
      return (GetTransect) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTransect setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTransect) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTransect setQuotaUser(java.lang.String quotaUser) {
      return (GetTransect) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTransect setUserIp(java.lang.String userIp) {
      return (GetTransect) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetTransect setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTransect set(String parameterName, Object value) {
      return (GetTransect) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTransect".
   *
   * This request holds the parameters needed by the transectendpoint server.  After setting any
   * optional parameters, call the {@link InsertTransect#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect}
   * @return the request
   */
  public InsertTransect insertTransect(com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect content) throws java.io.IOException {
    InsertTransect result = new InsertTransect(content);
    initialize(result);
    return result;
  }

  public class InsertTransect extends TransectendpointRequest<com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect> {

    private static final String REST_PATH = "transect";

    /**
     * Create a request for the method "insertTransect".
     *
     * This request holds the parameters needed by the the transectendpoint server.  After setting any
     * optional parameters, call the {@link InsertTransect#execute()} method to invoke the remote
     * operation. <p> {@link InsertTransect#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect}
     * @since 1.13
     */
    protected InsertTransect(com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect content) {
      super(Transectendpoint.this, "POST", REST_PATH, content, com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect.class);
    }

    @Override
    public InsertTransect setAlt(java.lang.String alt) {
      return (InsertTransect) super.setAlt(alt);
    }

    @Override
    public InsertTransect setFields(java.lang.String fields) {
      return (InsertTransect) super.setFields(fields);
    }

    @Override
    public InsertTransect setKey(java.lang.String key) {
      return (InsertTransect) super.setKey(key);
    }

    @Override
    public InsertTransect setOauthToken(java.lang.String oauthToken) {
      return (InsertTransect) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTransect setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTransect) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTransect setQuotaUser(java.lang.String quotaUser) {
      return (InsertTransect) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTransect setUserIp(java.lang.String userIp) {
      return (InsertTransect) super.setUserIp(userIp);
    }

    @Override
    public InsertTransect set(String parameterName, Object value) {
      return (InsertTransect) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTransect".
   *
   * This request holds the parameters needed by the transectendpoint server.  After setting any
   * optional parameters, call the {@link ListTransect#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTransect listTransect() throws java.io.IOException {
    ListTransect result = new ListTransect();
    initialize(result);
    return result;
  }

  public class ListTransect extends TransectendpointRequest<com.noisyflowers.landpks.server.gae.model.transectendpoint.model.CollectionResponseTransect> {

    private static final String REST_PATH = "transect";

    /**
     * Create a request for the method "listTransect".
     *
     * This request holds the parameters needed by the the transectendpoint server.  After setting any
     * optional parameters, call the {@link ListTransect#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListTransect#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTransect() {
      super(Transectendpoint.this, "GET", REST_PATH, null, com.noisyflowers.landpks.server.gae.model.transectendpoint.model.CollectionResponseTransect.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTransect setAlt(java.lang.String alt) {
      return (ListTransect) super.setAlt(alt);
    }

    @Override
    public ListTransect setFields(java.lang.String fields) {
      return (ListTransect) super.setFields(fields);
    }

    @Override
    public ListTransect setKey(java.lang.String key) {
      return (ListTransect) super.setKey(key);
    }

    @Override
    public ListTransect setOauthToken(java.lang.String oauthToken) {
      return (ListTransect) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTransect setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTransect) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTransect setQuotaUser(java.lang.String quotaUser) {
      return (ListTransect) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTransect setUserIp(java.lang.String userIp) {
      return (ListTransect) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTransect setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime afterDate;

    /**

     */
    public com.google.api.client.util.DateTime getAfterDate() {
      return afterDate;
    }

    public ListTransect setAfterDate(com.google.api.client.util.DateTime afterDate) {
      this.afterDate = afterDate;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTransect setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTransect set(String parameterName, Object value) {
      return (ListTransect) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTransect".
   *
   * This request holds the parameters needed by the transectendpoint server.  After setting any
   * optional parameters, call the {@link RemoveTransect#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTransect removeTransect(java.lang.String id) throws java.io.IOException {
    RemoveTransect result = new RemoveTransect(id);
    initialize(result);
    return result;
  }

  public class RemoveTransect extends TransectendpointRequest<Void> {

    private static final String REST_PATH = "transect/{id}";

    /**
     * Create a request for the method "removeTransect".
     *
     * This request holds the parameters needed by the the transectendpoint server.  After setting any
     * optional parameters, call the {@link RemoveTransect#execute()} method to invoke the remote
     * operation. <p> {@link RemoveTransect#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTransect(java.lang.String id) {
      super(Transectendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTransect setAlt(java.lang.String alt) {
      return (RemoveTransect) super.setAlt(alt);
    }

    @Override
    public RemoveTransect setFields(java.lang.String fields) {
      return (RemoveTransect) super.setFields(fields);
    }

    @Override
    public RemoveTransect setKey(java.lang.String key) {
      return (RemoveTransect) super.setKey(key);
    }

    @Override
    public RemoveTransect setOauthToken(java.lang.String oauthToken) {
      return (RemoveTransect) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTransect setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTransect) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTransect setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTransect) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTransect setUserIp(java.lang.String userIp) {
      return (RemoveTransect) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveTransect setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTransect set(String parameterName, Object value) {
      return (RemoveTransect) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTransect".
   *
   * This request holds the parameters needed by the transectendpoint server.  After setting any
   * optional parameters, call the {@link UpdateTransect#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect}
   * @return the request
   */
  public UpdateTransect updateTransect(com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect content) throws java.io.IOException {
    UpdateTransect result = new UpdateTransect(content);
    initialize(result);
    return result;
  }

  public class UpdateTransect extends TransectendpointRequest<com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect> {

    private static final String REST_PATH = "transect";

    /**
     * Create a request for the method "updateTransect".
     *
     * This request holds the parameters needed by the the transectendpoint server.  After setting any
     * optional parameters, call the {@link UpdateTransect#execute()} method to invoke the remote
     * operation. <p> {@link UpdateTransect#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect}
     * @since 1.13
     */
    protected UpdateTransect(com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect content) {
      super(Transectendpoint.this, "PUT", REST_PATH, content, com.noisyflowers.landpks.server.gae.model.transectendpoint.model.Transect.class);
    }

    @Override
    public UpdateTransect setAlt(java.lang.String alt) {
      return (UpdateTransect) super.setAlt(alt);
    }

    @Override
    public UpdateTransect setFields(java.lang.String fields) {
      return (UpdateTransect) super.setFields(fields);
    }

    @Override
    public UpdateTransect setKey(java.lang.String key) {
      return (UpdateTransect) super.setKey(key);
    }

    @Override
    public UpdateTransect setOauthToken(java.lang.String oauthToken) {
      return (UpdateTransect) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTransect setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTransect) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTransect setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTransect) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTransect setUserIp(java.lang.String userIp) {
      return (UpdateTransect) super.setUserIp(userIp);
    }

    @Override
    public UpdateTransect set(String parameterName, Object value) {
      return (UpdateTransect) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Transectendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Transectendpoint}. */
    @Override
    public Transectendpoint build() {
      return new Transectendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TransectendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTransectendpointRequestInitializer(
        TransectendpointRequestInitializer transectendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(transectendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
